### PR TITLE
Fix Bothub classifier and add tests

### PR DESCRIPTION
**Pull request by matmsa27**
Hi @nicpottier , we fix it the `ClassifierTypeBothub` for `bh` and add BotHub type on the test list for run tests.

Thanks a lot.
Regards

### CODE REVIEW

**Comment by nicpottier** [comment]
Thanks, ya, that's kind of a shame, we are using a longer type for classifier types since that makes it easier for everyone. Why don't we change the type on the Bothub type to `bothub` on the RapidPro side. (I'm fine with that PR and this one in adding that) A quick DB shell can be used to update any classifiers already created but at least will keep things in sync.

**Comment by matmsa27** [comment]
Hmmm, yeah make sense. I opened a PR for RapidPro [here](https://github.com/nyaruka/rapidpro/pull/2597). I will change `classifier_type` on `mailroom_db.py` to `bothub`, and I'll change slug on `classifiers/types/bothub/type.py` for `bothub`.

Here in this PR I'll remove the change for `bh` and keep `bothub`, and generate a new `mailroom_test.dump`.

Can I proceed with these observations?
Thanks a lot.

**Comment by nicpottier** [comment]
Yep, that'd be perfect!

**Review by nicpottier — APPROVED** [review]

**Comment by nicpottier** [comment]
Thanks guys!

**Pull request merged**
