### PR TITLE
Only update runs with expires on in the future

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Can you give more context for this?

**Comment by norkans7** [comment]
The engine and the expiration task are trying to update the same row at the same time and that will cause the transaction to roll back and the archiver will fail to archive those runs.

https://sentry.io/organizations/nyaruka/issues/1948479022/?project=1285856&query=is%3Aunresolved

https://sentry.io/organizations/nyaruka/issues/1948479054/?project=1285856&query=is%3Aunresolved

https://sentry.io/organizations/nyaruka/issues/586214771/?project=1205568&query=is%3Aunresolved

My understanding here is that we allow the engine to update runs having expires_on in the future so its query and the expirations tasks will always be operating to different rows

**Comment by nicpottier** [comment]
Not updating the run seems way worse. We then have moved the run forward in the session but aren't updating the DB? That's not what we want.

**Comment by norkans7** [comment]
So we fail the session or expire the run in the sprint?

**Comment by nicpottier** [comment]
I'm not actually sure what the right fix is. If this is a race between us resuming a run and expiring a run then we either need some kind of lock or we need to deal with the deadlock properly. IE, if the transaction fails in updating the run here then we need to make sure the session isn't being updated as well.

We need to look at more scenarios to really see what the right thing to do is based on real life examples.

**Pull request closed without merging**
