### PR TITLE
🚨 Fix create contact failing to start

### PR DESCRIPTION
**Pull request by nicpottier**
Looks like a refactor in where we declared org caused us to skip asset creation. Yet again proving that if it isn't tested it is broken.

### CODE REVIEW

**Review by rowanseymour — APPROVED** [review]
is there a name for that law?

**Comment by nicpottier** [comment]
I can't find a name for it. Open to suggestions.. 

"Untested Code Always Breaks" UCAB?
"All Untested Code Eventually Breaks" AUCEB?

**Comment by rowanseymour** [comment]
Skip Tests, Fix Later (STFL)

**Comment by nicpottier** [comment]
Skip Tests, Fix in Update (STFU)
Skip Tests, All Broken (STAB)

**Comment by rowanseymour** [comment]
hehehe darn it couldn't think of a U

**Comment by nicpottier** [comment]
Skip Tests, Undeniably Broken (STUB)

**Comment by ericnewcomer** [comment]
Skipped Test Often Problems (STOP)

**Pull request merged**
